name: Build

on:
  push:
    branches: 
      - main

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout Code
        uses: actions/checkout@v1

      - 
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - 
        name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      -
        name: copy index.html to deploy folder (./dist)
        run: |
          cp article/index.html ./dist/
          cp article/bibliography.bib ./dist/
          cp -r article/images ./dist/images
          cp -r article/notebook ./dist/notebook
      - 
        name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: dist
        env:
          GITHUB_PAT: ${{ secrets.ANDREAS_GH_PAT }}